name=hetfo
version=1.0.0
author=CyberSecLab
maintainer=Teszt Elek
sentence=Semmi extra, ez egy demó.
paragraph=Ez egy példa a saját könyvtár létrehozására.
category=Uncategorized
url=https://github.com/cyberseclabor/hetfo
architectures=esp32
