name=hetfo
version=1.0.0
author=CyberSecLab
maintainer=Teszt Elek
sentence=Egy rövid leírás arról, mit csinál a könyvtár.
paragraph=Itt részletesebben is kifejtheted. ESP32-höz optimalizálva.
category=Uncategorized
url=https://github.com/cyberseclabor/hetfo
architectures=esp32